name: Harden Runner Block Host

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Curl Wikipedia
        run: |
          echo "Attempting to reach Wikipedia... (expecting to fail)"
          curl -I https://www.wikipedia.org