name: Leak No Protection

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Curl Wikipedia
        run: |
          echo "Attempting to reach Wikipedia..."
          curl -I https://www.wikipedia.org

      - name: Sus Activity
        run: |
          echo " Secret: ${{ secrets.LEAKEAD_SECRET }}"